on:
  workflow_dispatch:

name: Publish Xbuild container

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: do build
        run: docker build -t xbuild:latest .
      - name: do docker login
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $TOKEN | docker login ghcr.io -u sjfalken --password-stdin
      - name: do push
        run: docker push ghcr.io/sjfalken/xbuild:latest
    
